name: API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ windows-latest, ubuntu-latest ]

    runs-on: ${{matrix.os}}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m venv venv
        .\venv\Scripts\Activate.ps1
        pip install -r requirements.txt


    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/test_api.py
